server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**


  security:
    user:
      name: test@naver.com
      password: 1q2w3e4r1!
    oauth2:
      client:
        registration:
          google:
            clientId: 837490359219-thp8ungeich96coes8oedbsfhiv945bd.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          naver:
            clientId: s0ki1SBe8mVOE3Y1mOS7
            clientSecret: 7HBiuZq4F7
            scope:
              - email
              - name
            clientName: Naver
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8000/login/oauth2/code/naver
        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.cdvypkiasxqr.ap-northeast-2.rds.amazonaws.com:3306/stussy-20220930
    username: admin
    password: 1q2w3e4r



mybatis:
  mapper-locations:
    - /mappers/*.xml
